"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight,Check} from "lucide-react";
const steps=[
 {label:"Room",options:[["Living","A welcoming anchor for the room."],["Bedroom","A calmer, more considered setting."],["Dining","A table-led space for gathering."],["Study","Focused furniture with quiet character."]]},
 {label:"Feeling",options:[["Warm","Natural textures and softer forms."],["Minimal","Clean lines and visual breathing room."],["Statement","One defining piece with presence."],["Timeless","Balanced shapes made to stay relevant."]]}
];
export function HomeFinder(){const [step,setStep]=useState(0);const [choice,setChoice]=useState(steps[0].options[0][0]);const current=steps[step];const copy=useMemo(()=>current.options.find(o=>o[0]===choice)?.[1]||"",[current,choice]);return <section data-tone="#e7ddd0" className="border-y border-line bg-sand py-24 md:py-32"><div className="container grid gap-12 md:grid-cols-[.7fr_1.3fr] md:items-end"><div><p className="eyebrow text-wood">Find your starting point</p><h2 className="display mt-4 text-5xl md:text-6xl">Tell us what the room needs.</h2><p className="mt-6 max-w-md text-sm leading-7 text-ink/60">A small guided starting point for browsing the collection. Choose a room, then a feeling.</p><div className="mt-8 flex gap-2">{steps.map((s,i)=><button key={s.label} onClick={()=>setStep(i)} className={`border px-4 py-2 text-[10px] font-bold uppercase tracking-[.16em] transition ${step===i?"border-ink bg-ink text-paper":"border-ink/20"}`}>{i+1} · {s.label}</button>)}</div></div><div><div className="grid gap-px overflow-hidden border border-ink/10 bg-ink/10 sm:grid-cols-2">{current.options.map(([title,desc])=><button key={title} onClick={()=>setChoice(title)} className={`group min-h-[150px] bg-paper p-6 text-left transition duration-500 hover:bg-[#f1e9df] ${choice===title?"ring-1 ring-inset ring-ink":""}`}><div className="flex items-start justify-between"><span className="display text-3xl">{title}</span>{choice===title&&<Check size={17}/>}</div><p className="mt-8 max-w-xs text-sm leading-6 text-ink/55">{desc}</p></button>)}</div><div className="mt-7 flex flex-col justify-between gap-5 border-t border-ink/15 pt-6 sm:flex-row sm:items-center"><p className="text-sm text-ink/65"><span className="font-bold text-ink">{choice}.</span> {copy}</p><Link href="/contact" data-cursor="ENQUIRE" className="luxury-button inline-flex shrink-0 items-center gap-3 border-b border-ink pb-2 text-xs font-bold uppercase tracking-[.15em]">Talk to HnH <ArrowRight size={15}/></Link></div></div></div></section>}
