import Link from "next/link";
import {ArrowUpRight} from "lucide-react";
import {Reveal} from "@/components/reveal";
import {MaskReveal} from "@/components/mask-reveal";
import {StudioImage} from "@/components/studio-image";

const materials=[["Solid wood","Warm grain, honest variation and a surface that gains character with use.","/images/materials/solid-wood.jpg"],["Natural finishes","Finishes that keep the material present rather than hiding it.","/images/materials/natural-finish.jpg"],["Upholstery","Tactile fabrics selected around comfort, use and the feeling of a room.","/images/materials/upholstery.jpg"],["Details","Handles, edges, joinery and the small decisions that make a piece feel resolved.","/images/materials/details.jpg"]];

export default function MaterialsPage(){return <main><section className="container py-20 md:py-28"><Reveal><p className="eyebrow text-wood">Material library</p></Reveal><MaskReveal><h1 className="display mt-4 max-w-5xl text-6xl leading-[.95] md:text-8xl">The material is part of the furniture.</h1></MaskReveal><Reveal delay={140}><p className="mt-9 max-w-2xl text-lg leading-8 text-ink/65">Explore the surfaces, textures and finishing choices that shape how a piece looks, feels and lives over time.</p></Reveal></section><section className="border-y border-line bg-[#eee7de]"><div className="container grid md:grid-cols-2">{materials.map(([name,copy,img],i)=><article key={name} className="border-b border-line p-5 md:p-8 md:[&:nth-child(odd)]:border-r"><div className="aspect-[1.12/1] overflow-hidden"><StudioImage src={img} alt={name}/></div><p className="eyebrow mt-7 text-wood">0{i+1}</p><h2 className="display mt-3 text-4xl">{name}</h2><p className="mt-4 max-w-md text-sm leading-7 text-ink/60">{copy}</p></article>)}</div></section><section className="container py-24 text-center"><Reveal><p className="eyebrow text-wood">Choose with confidence</p><h2 className="display mx-auto mt-4 max-w-3xl text-5xl md:text-6xl">Need help matching a finish to your room?</h2><Link href="/contact" className="luxury-button mt-8 inline-flex items-center gap-3 bg-ink px-6 py-4 text-xs font-bold uppercase tracking-[.14em] text-paper">Talk to HnH <ArrowUpRight size={16}/></Link></Reveal></section></main>;}
